---
params:
  level: neighbourhood
  neighbourhood: North St.James Town
output:
  html_document:
    df_print: paged
    css: ../app/www/style.css
knit: pagedown::chrome_print
---

```{r setup, include=FALSE}
devtools::load_all()
library(htmltools)
library(knitr)
library(leaflet)
library(mapview)
library(tmap)
library(ceramic)
library(tmaptools)
library(dplyr)

knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE,
  dpi = 300, out.width = "95%", fig.align = "center"
)

level <- params$level
neighbourhood <- params$neighbourhood
compare <- level == "neighbourhood"

title <- switch(level,
  "neighbourhood" = neighbourhood,
  "city" = "City of Toronto"
)

dataset <- lemr:::determine_dataset_from_level(level, neighbourhood)

legend <- if (level == "neighbourhood") {
  legend_label <- glue::glue("A legend showing {neighbourhood} (dark blue) versus City of Toronto (grey), used for plots on this page.")
  shiny::HTML(glue::glue("<div role = 'img' aria-label = '{legend_label}'>{lemr::create_neighbourhood_legend(neighbourhood)}</div>"))
}
```

<!-- <div style = "background-color: var(--main-color) !important; color: white; height: 5em; text-align: center;"> -->
# `r title`
<!-- </div> -->

```{r map-alt-text}
map_alt_text <- glue::glue("A map of {area} showing the locations of apartment buildings, above guideline increase applications, and tenant defense fund grant recipients.", area = ifelse(level == "city", "Toronto", neighbourhood))
```

<div class = "row vertical-align">
  <div class = "col-sm-8">
```{r map-prep}
if (level == "neighbourhood") {
  map_data <- lemr::neighbourhoods %>%
    dplyr::filter(neighbourhood == !!neighbourhood)

  bbox <- tmaptools::bb(map_data, ext = 1.1) %>%
    unname()

  map_buildings <- lemr::buildings %>%
    dplyr::filter(neighbourhood == !!neighbourhood)

  basemap <- cc_location(
    loc = raster::extent(bbox),
    base_url = "https://api.mapbox.com/styles/v1/purposeanalytics/cksw80iwn155y1anq5l1f0v5n/tiles/512/{zoom}/{x}/{y}",
    verbose = FALSE
  )
} else {
  map_data <- lemr::toronto

  bbox <- tmaptools::bb(map_data, ext = 1.1) %>%
    unname()

  map_buildings <- lemr::buildings

  basemap <- cc_location(
    loc = raster::extent(bbox),
    zoom = 9,
    base_url = "https://api.mapbox.com/styles/v1/purposeanalytics/cksw80iwn155y1anq5l1f0v5n/tiles/512/{zoom}/{x}/{y}",
    verbose = FALSE
  )
}

add_circle_layer <- function(map, data, colour, level) {
  if (nrow(data) == 0) {
    return(map)
  }

  size <- switch(level,
    city = 0.1,
    neighbourhood = 0.25
  )
  shape <- switch(level,
    city = 16,
    neighbourhood = 21
  )

  map +
    tm_shape(data) +
    tm_symbols(size = size, col = colour, shape = shape, border.col = "white")
}
```

```{r map, dpi = 96, out.width = "100%", eval = TRUE}
tm_shape(basemap) +
  tm_rgb() +
  tm_shape(map_data) +
  tm_borders(col = lemr:::main_colour, lwd = 2) %>%
  # Apartment buildings
  add_circle_layer(dplyr::filter(map_buildings, apartment, property_type == "Privately owned"), lemr:::rental_supply_colors()[["Apartment"]], level = level) %>%
  add_circle_layer(dplyr::filter(map_buildings, apartment, property_type == "Toronto Community Housing"), lemr:::rental_supply_colors()[["Toronto Community Housing"]], level = level) %>%
  add_circle_layer(dplyr::filter(map_buildings, apartment, property_type == "Social housing"), lemr:::rental_supply_colors()[["Other Non-Market"]], level = level) %>%
  # Rooming houses
  add_circle_layer(dplyr::filter(map_buildings, rooming_house, rooming_house_status == "Licensed 2018 onwards"), lemr:::rooming_house_colors()[["Licensed 2018 onwards"]], level = level) %>%
  add_circle_layer(dplyr::filter(map_buildings, rooming_house, rooming_house_status == "Licensed prior to 2018"), lemr:::rooming_house_colors()[["Licensed prior to 2018"]], level = level)
```
  </div>
  <div class = "col-sm-4">
  
```{r plot-legend}
shiny::tagList(
  purrr::pmap(
    dplyr::tibble(
      color = c("Apartment", "Toronto Community Housing", "Other Non-Market"),
      wording = c("Privately owned", "Toronto Community Housing", "Other non-market")
    ),
    function(color, wording, data_suffix) {
      lemr:::create_circle_legend(lemr:::rental_supply_colors()[[color]],
        glue::glue("{wording} apartment buildings"),
        alt_text = glue::glue("A legend showing the colour of the points of {wording} apartment buildings.")
      )
    }
  ),
  purrr::pmap(
    dplyr::tibble(
      filter = c("Licensed prior to 2018", "Licensed 2018 onwards")
    ),
    function(filter) {
      lemr:::create_circle_legend(lemr:::rooming_house_colors()[[filter]],
        glue::glue("Rooming houses, {wording}",
          wording = tolower(filter)
        ),
        alt_text = glue::glue("A legend showing the colour of the points of rooming houses {tolower(filter)}.")
      )
    }
  )
)
```
  
  </div>
</div>

<hr>

<div class = "row">

  <div class = "col-sm-6">

## Summary statistics
```{r summary-statistics}
lemr:::summary_statistics_table(dataset)
```
  
### Estimated rental supply (2016)

```{r rental-supply, fig.alt = lemr:::rental_supply_plot_alt_text(level, neighbourhood), fig.height = 0.5}
lemr:::rental_supply_plot(dataset, static = TRUE)
```

```{r rental-supply-table}
lemr:::rental_supply_single_table(dataset)
```

  </div>
  
  <div class = "col-sm-6">
### Estimated supply of low-end of market rental

```{r lem}
lemr:::display_lem(dataset)
```
  </div>
</div>

<hr>

<div style = "display:block; clear:both; page-break-after:always;"></div>
<div class = "row">
  <div class = "col-sm-6">
  
```{r output = "asis"}
legend
```

```{r apartment-building-units, fig.alt = lemr:::number_of_units_plot_alt_text(level, neighbourhood), fig.height = 1.75}
number_of_units <- lemr:::get_measure(dataset, "number_of_units")
number_of_units_formatted <- lemr:::format_measure(number_of_units, "number_of_units")

lemr:::number_of_units_number(number_of_units_formatted) %>%
  h3()

lemr:::number_of_units_breakdown(dataset) %>%
  lemr:::bigger_padded()

lemr:::number_of_units_description(level, neighbourhood, number_of_units, number_of_units_formatted) %>%
  p()

lemr:::number_of_units_plot(dataset, compare, static = TRUE)
```

```{r apartment-building-evaluation, fig.alt = lemr:::apartment_building_evaluation_plot_alt_text(level, neighbourhood), fig.height = 1.75}
apartment_building_evaluation <- lemr:::get_measure(dataset, "apartment_building_evaluation")
apartment_building_evaluation_formatted <- lemr:::format_measure(apartment_building_evaluation, "apartment_building_evaluation")

lemr:::apartment_building_evaluation_number(apartment_building_evaluation_formatted) %>%
  h3()

lemr:::apartment_building_evaluation_none(apartment_building_evaluation_formatted) %>%
  p() %>%
  lemr:::padded()

lemr:::apartment_building_evaluation_description(level, neighbourhood, apartment_building_evaluation, apartment_building_evaluation_formatted) %>%
  p()

lemr:::apartment_building_evaluation_plot(dataset, compare, static = TRUE)
```

### Rooming house licenses (2020)

```{r rooming-houses}
lemr:::display_rooming_houses(dataset, compare = compare)
```

### AGI Applications (2016 to 2020) and TDF Grants (2018 to 2020)

```{r}
lemr:::agi_tdf_description(level, neighbourhood) %>%
  p()

lemr:::display_agi_tdf_buildings(dataset, compare)

lemr:::agi_non_apartments(dataset, level, neighbourhood) %>%
  p()
```
  </div>

  <div class = "col-sm-6">
  
```{r core-housing-need, fig.alt = lemr:::core_housing_need_plot_alt_text(level, neighbourhood), fig.height = 1.75}
core_housing_need <- lemr:::get_measure(dataset, "core_housing_need")
core_housing_need_formatted <- lemr:::format_measure(core_housing_need, "core_housing_need")

lemr:::core_housing_need_number(core_housing_need_formatted) %>%
  h3()

lemr:::core_housing_need_description(level, neighbourhood, core_housing_need, core_housing_need_formatted) %>%
  p()

lemr:::core_housing_need_plot(dataset, compare, static = TRUE)
```

```{r evictions, fig.alt = lemr:::evictions_plot_alt_text(level, neighbourhood), fig.height = 1.75}
evictions <- lemr:::get_measure(dataset, "evictions")
evictions_formatted <- lemr:::format_measure(evictions, "evictions")

lemr:::evictions_number(evictions_formatted) %>%
  h3()

lemr:::evictions_description(level, neighbourhood, evictions, evictions_formatted) %>%
  p()

lemr:::evictions_plot(dataset, compare, static = TRUE)
```

```{r vacancy-rate, fig.alt = lemr:::vacancy_rate_plot_alt_text(level, neighbourhood), fig.height = 1.75}
vacancy_rate <- lemr:::get_measure(dataset, "vacancy_rate_2020")
vacancy_rate_formatted <- lemr:::format_measure(vacancy_rate, "vacancy_rate")

lemr:::vacancy_rate_number(vacancy_rate_formatted) %>%
  h3()

lemr:::evictions_description(level, neighbourhood, vacancy_rate, vacancy_rate_formatted) %>%
  p()

lemr:::vacancy_rate_plot(dataset, compare, static = TRUE)
```

### Proximity to services (2020)

```{r amenity-density, fig.alt = lemr:::amenity_density_plot_alt_text(level, neighbourhood), fig.height = 2}
lemr:::amenity_density_description(level, neighbourhood) %>%
  p()

lemr:::amenity_density_plot(dataset, compare, static = TRUE)

lemr:::generate_table(dataset, "amenity_density", compare, "Proximity to services", "Percent") %>%
  kableExtra::footnote(general = "A very small number of areas have unknown proximity to services, so values may not add up to 100%.")
```
  </div>
</div>

<hr>

##
<div style = "display:block; clear:both; page-break-after:always;"></div>

## Housing characteristics 

<div class = "row">
  <div class = "col-sm-6">  
  
```{r output = "asis"}
legend
```

```{r apartment-buildings, fig.alt = lemr:::number_of_apartments_plot_alt_text(level, neighbourhood), fig.height = 1.75}
number_of_apartments <- lemr:::get_measure(dataset, "number_of_buildings")
number_of_apartments_formatted <- lemr:::format_measure(number_of_apartments, "number_of_buildings")

lemr:::number_of_apartments_number(number_of_apartments_formatted) %>%
  h3()

lemr:::number_of_apartments_breakdown(dataset) %>%
  lemr:::bigger_padded()

lemr:::number_of_apartments_description(level, neighbourhood, number_of_apartments, number_of_apartments_formatted) %>%
  p()

lemr:::number_of_apartments_plot(dataset, compare, static = TRUE)
```
  
### Housing structure type (2016)

```{r structure-type, fig.alt = lemr:::structure_type_plot_alt_text(level, neighbourhood), fig.height = 2.5}
lemr:::structure_type_description(level, neighbourhood) %>%
  p()

lemr:::structure_type_plot(dataset, compare, static = TRUE)

lemr:::generate_table(dataset, "structure_type", compare, "Housing Structure Type", "Percent")
```

```{r shelter-cost, fig.alt = lemr:::average_renter_shelter_cost_plot_alt_text(level, neighbourhood), fig.height = 1.75}
shelter_cost <- lemr:::get_measure(dataset, "average_renter_shelter_cost")
shelter_cost_formatted <- lemr:::format_measure(shelter_cost, "average_renter_shelter_cost")

lemr:::shelter_cost_number(shelter_cost_formatted, level) %>%
  h3()

lemr:::average_renter_shelter_cost_description(level, neighbourhood, shelter_cost, shelter_cost_formatted) %>%
  p()

lemr:::average_renter_shelter_cost_plot(dataset, compare, static = TRUE)
```
  </div>
  
  <div class = "col-sm-6">
  
```{r unaffordable-housing, fig.alt = lemr:::unaffordable_housing_plot_alt_text(level, neighbourhood), fig.height = 1.75}
unaffordable_housing <- lemr:::get_measure(dataset, "unaffordable_housing")
unaffordable_housing_formatted <- lemr:::format_measure(unaffordable_housing, "unaffordable_housing")

lemr:::unaffordable_housing_number(unaffordable_housing_formatted, level) %>%
  h3()

lemr:::unaffordable_housing_description(level, neighbourhood, unaffordable_housing, unaffordable_housing_formatted) %>%
  p()

lemr:::unaffordable_housing_plot(dataset, compare, static = TRUE)
```

### Households by tenure (2016)

```{r household-tenure, fig.alt = lemr:::household_tenure_plot_alt_text(level, neighbourhood), fig.height = 1.75}
lemr:::household_tenure_description(level, neighbourhood) %>%
  p()

lemr:::household_tenure_plot(dataset, compare, static = TRUE)

lemr:::generate_table(dataset, "household_tenure", compare, "Housing Structure Type", "Percent")
```

### Number of bedrooms (2016)

```{r bedrooms, fig.alt = lemr:::bedrooms_plot_alt_text(level, neighbourhood), fig.height = 2.5}
lemr:::bedrooms_description(level, neighbourhood) %>%
  p()

lemr:::bedrooms_plot(dataset, compare, static = TRUE)

lemr:::generate_table(dataset, "bedrooms", compare, "Housing Structure Type", "Percent")
```
  </div>
</div>

<hr>

##
<div style = "display:block; clear:both; page-break-after:always;"></div>

## Sociodemographic characteristics

<div class = "row">
  <div class = "col-sm-6">  
  
```{r output = "asis"}
legend
```
  
```{r population-density, fig.alt = lemr:::population_density_plot_alt_text(level, neighbourhood), fig.height = 1.75}
population_density <- lemr:::get_measure(dataset, "population_density")
population_density_formatted <- lemr:::format_measure(population_density, "population_density")

lemr:::population_density_number(population_density_formatted) %>%
  h3()

lemr:::population_density_description(level, neighbourhood, population_density, population_density_formatted) %>%
  p()

lemr:::population_density_plot(dataset, compare, static = TRUE)
```

```{r population-change, fig.alt = lemr:::population_change_plot_alt_text(level, neighbourhood), fig.height = 1.75}
population_change <- lemr:::get_measure(dataset, "population_change")
population_change_formatted <- lemr:::format_measure(population_change, "population_change")

lemr:::population_change_number(population_change_formatted) %>%
  h3()

lemr:::population_change_description(level, neighbourhood, population_change, population_change_formatted) %>%
  p()

lemr:::population_change_plot(dataset, compare, static = TRUE)
```

### Average Total Household Income (2016)

```{r average-total-household-income, fig.alt = lemr:::average_total_household_income_plot_alt_text(level, neighbourhood), fig.height = 1.75}
lemr:::average_total_household_income_description(level, neighbourhood) %>%
  p()

lemr:::average_total_household_income_plot(dataset, compare, static = TRUE)

lemr:::generate_table(dataset, "average_total_income", compare, "Household Size", "Percent", format = "dollar")
```

```{r lim-at, fig.alt = lemr:::lim_at_plot_alt_text(level, neighbourhood), fig.height = 1.75}
lim_at <- lemr:::get_measure(dataset, "lim_at")
lim_at_formatted <- lemr:::format_measure(lim_at, "lim_at")

lemr:::lim_at_number(lim_at_formatted, level) %>%
  h3()

lemr:::lim_at_description(level, neighbourhood, lim_at, lim_at_formatted) %>%
  p()

lemr:::lim_at_plot(dataset, compare, static = TRUE)
```
  </div>
  <div class = "col-sm-6">

### Household size (2016)

```{r household-size, fig.alt = lemr:::household_size_plot_alt_text(level, neighbourhood), fig.height = 2.5}
lemr:::household_size_description(level, neighbourhood) %>%
  p()

lemr:::household_size_plot(dataset, compare, static = TRUE)

lemr:::generate_table(dataset, "household_size", compare, "Household Size", "Percent")
```

  <div class = "visible-minority">
```{r visible-minority, fig.alt = lemr:::visible_minority_plot_alt_text(level, neighbourhood), fig.height = 4}
lemr:::visible_minority_number(dataset, level) %>%
  h3()

lemr:::visible_minority_description(level, neighbourhood) %>%
  p()

lemr:::visible_minority_plot(dataset, compare, static = TRUE)

lemr:::generate_table(dataset, "visible_minority", compare, "Visible Minority Group", "Percent") %>%
  kableExtra::footnote(general = '"n.i.e." = not included elsewhere') %>%
  kableExtra::kable_styling(bootstrap_options = "condensed")
```
  </div>
  </div>
</div>
