---
params:
  level: neighbourhood
  neighbourhood: Danforth
output:
  html_document:
    df_print: paged
    css: ../app/www/style.css
---

```{r setup, include=FALSE}
library(lemur)
library(htmltools)
library(knitr)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, dpi = 300, out.width = "100%", fig.pos = "!H")

knitr::opts_template$set(distribution = list(
  fig.height = 1
))

html_output <- is_html_output()
output <- ifelse(html_output, "html", "pdf")

if (html_output) {
  output <- "html"
  format_paragraph <- htmltools::p
} else {
  output <- "pdf"
  format_paragraph <- function(x) {
    cat(x, "\n")
  }
}

level <- params$level
neighbourhood <- params$neighbourhood
compare <- level == "neighbourhood"

title <- switch(level,
  "neighbourhood" = neighbourhood,
  "city" = "City of Toronto"
)

dataset <- lemur:::determine_dataset_from_level(level, neighbourhood)
```

---
title: `r title`
---

```{r population}
glue::glue('Population: {scales::comma(dataset[["population"]])} ({scales::comma(dataset[["households"]])} households)') %>%
  lemur:::bigger_padded()
```

## Population change

```{r population-change, opts.label = "distribution", fig.alt = lemur:::population_change_plot_alt_text(level, neighbourhood)}
population_change <- lemur:::get_measure(dataset, "population_change")
population_change_formatted <- lemur:::format_measure(population_change, "population_change")

lemur:::population_change_number(population_change_formatted) %>%
  lemur:::bigger_padded()

lemur:::population_change_description(level, neighbourhood, population_change, population_change_formatted) %>%
  format_paragraph() %>%
  lemur:::bigger_padded()

lemur:::population_change_plot(dataset, compare)
```

## Population density

```{r population-density, opts.label = "distribution", fig.alt = lemur:::population_density_plot_alt_text(level, neighbourhood)}
population_density <- lemur:::get_measure(dataset, "population_density")
population_density_formatted <- lemur:::format_measure(population_density, "population_density")

lemur:::population_density_number(population_density_formatted) %>%
  lemur:::bigger_padded()

lemur:::population_density_description(level, neighbourhood, population_density, population_density_formatted) %>%
  format_paragraph() %>%
  lemur:::bigger_padded()

lemur:::population_density_plot(dataset, compare)
```

## Household size 

```{r household-size, fig.alt = lemur:::household_size_plot_alt_text(level, neighbourhood), fig.height = 2}
lemur:::household_size_description(level, neighbourhood) %>%
  format_paragraph()

lemur:::household_size_plot(dataset, compare)

lemur:::generate_table(dataset, "household_size", compare, "Household Size", "Percent", output = output)
```

## Average Total Household Income 

```{r average-total-household-income, fig.alt = lemur:::average_total_household_income_plot_alt_text(level, neighbourhood), fig.height = 1}
lemur:::average_total_household_income_description(level, neighbourhood) %>%
  format_paragraph()

lemur:::average_total_household_income_plot(dataset, compare)

lemur:::generate_table(dataset, "average_total_income", compare, "Household Size", "Percent", format = "dollar", output = output)
```

## Unaffordable housing

```{r unaffordable-housing, opts.label = "distribution", fig.alt = lemur:::unaffordable_housing_plot_alt_text(level, neighbourhood)}
unaffordable_housing <- lemur:::get_measure(dataset, "unaffordable_housing")
unaffordable_housing_formatted <- lemur:::format_measure(unaffordable_housing, "unaffordable_housing")

lemur:::unaffordable_housing_number(unaffordable_housing_formatted) %>%
  lemur:::bigger_padded()

lemur:::unaffordable_housing_city(level) %>%
  lemur:::bigger_padded()

lemur:::unaffordable_housing_description(level, neighbourhood, unaffordable_housing, unaffordable_housing_formatted) %>%
  format_paragraph()

lemur:::unaffordable_housing_plot(dataset, compare)
```

## Low-income measure after tax

```{r lim-at, opts.label = "distribution", fig.alt = lemur:::lim_at_plot_alt_text(level, neighbourhood)}
lim_at <- lemur:::get_measure(dataset, "lim_at")
lim_at_formatted <- lemur:::format_measure(lim_at, "lim_at")

lemur:::lim_at_number(lim_at_formatted) %>%
  lemur:::bigger_padded()

lemur:::lim_at_city(level) %>%
  lemur:::bigger_padded()

lemur:::lim_at_description(level, neighbourhood, lim_at, lim_at_formatted) %>%
  format_paragraph()

lemur:::lim_at_plot(dataset, compare)
```

## Visible minority population

```{r visible-minority, fig.alt = lemur:::visible_minority_plot_alt_text(level, neighbourhood), fig.height = 4}
lemur:::visible_minority_number(dataset)  %>%
  lemur:::bigger_padded()

lemur:::visible_minority_city(level) %>%
  lemur:::bigger_padded()

lemur:::visible_minority_description(level, neighbourhood) %>%
  format_paragraph()

lemur:::visible_minority_plot(dataset, compare)

lemur:::generate_table(dataset, "visible_minority", compare, "Visible Minority Group", "Percent", output = output) %>%
  kableExtra::footnote(general = '"n.i.e." = not included elsewhere')
```

## Housing structure type

```{r structure-type, fig.alt = lemur:::structure_type_plot_alt_text(level, neighbourhood), fig.height = 2}
lemur:::structure_type_description(level, neighbourhood) %>%
  format_paragraph()

lemur:::structure_type_plot(dataset, compare)

lemur:::generate_table(dataset, "structure_type", compare, "Housing Structure Type", "Percent", output = output)
```

## Number of bedrooms

```{r bedrooms, fig.alt = lemur:::bedrooms_plot_alt_text(level, neighbourhood), fig.height = 2}
lemur:::bedrooms_description(level, neighbourhood) %>%
  format_paragraph()

lemur:::bedrooms_plot(dataset, compare)

lemur:::generate_table(dataset, "bedrooms", compare, "Housing Structure Type", "Percent", output = output)
```

# Households by tenure

```{r household-tenure, fig.alt = lemur:::household_tenure_plot_alt_text(level, neighbourhood), fig.height = 1}
lemur:::household_tenure_description(level, neighbourhood) %>%
  format_paragraph()

lemur:::household_tenure_plot(dataset, compare)

lemur:::generate_table(dataset, "household_tenure", compare, "Housing Structure Type", "Percent", output = output)
```

## Average shelter cost for renters

```{r shelter-cost, opts.label = "distribution", fig.alt = lemur:::average_renter_shelter_cost_plot_alt_text(level, neighbourhood)}
shelter_cost <- lemur:::get_measure(dataset, "average_renter_shelter_cost")
shelter_cost_formatted <- lemur:::format_measure(shelter_cost, "average_renter_shelter_cost")

lemur:::shelter_cost_number(shelter_cost_formatted) %>%
  lemur:::bigger_padded()

lemur:::shelter_cost_city(level) %>%
  lemur:::bigger_padded()

lemur:::average_renter_shelter_cost_description(level, neighbourhood, shelter_cost, shelter_cost_formatted) %>%
  format_paragraph()

lemur:::average_renter_shelter_cost_plot(dataset, compare)
```
