name: Deployment

on: 
  push:
    tags:
      - v*
  schedule:
    - cron: "*/20 * * * *"


jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Main
        uses: actions/checkout@main
      - uses: r-lib/actions/setup-r@master
      
      - name: Install shiny
        run: |
          install.packages(c("shiny", "rsconnect"), type = "binary")
        shell: Rscript {0}
        
      - name: Lemr Files
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='username', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp(appName = 'appname')" 
      
      - run: docker_run
          e- HOST =  ${{ secrets.REMOTE_HOST }}
          e- USERNAME =  ${{ secrets.REMOTE_USER }}
          e- KEY = ${{ secrets.SSH_KEY }}
          e- PASSPHRASE = ${{ secrets.SSH_KEY_PASSPHRASE }}
          e- TARGET = ${{ secrets.REMOTE_APP_DIR }}
          main
