name: Deployment

on: 
  push:
    tags:
      - v*
  schedule:
    - cron: "*/20 * * * *"


jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Main
        uses: actions/checkout@main
      - uses: r-lib/actions/setup-r@master
      
      - name: Install shiny
        run: |
          install.packages(c("shiny", "rsconnect"))
        shell: Rscript {0}
        
 
      - name: Docker Commit
        run: docker_run
          e- HOST =  ${{ secrets.REMOTE_HOST }}
          e- USERNAME =  ${{ secrets.REMOTE_USER }}
          e- KEY = ${{ secrets.SSH_KEY }}
          e- PASSPHRASE = ${{ secrets.SSH_KEY_PASSPHRASE }}
          e- TARGET = ${{ secrets.REMOTE_APP_DIR }}
          main
          
      - name: R Commit
        run: |
          Rscript -e "rsconnect::setAccountInfo(name= ${{ secrets.REMOTE_USER }}, token=${{secrets.SSH_KEY}}, secret=${{secrets.SSH_KEY_PASSPHRASE}})"
          Rscript -e "rsconnect::deployApp()" 
      
