---
title: "Stories2"
date: "9/21/2021"
output:
  pdf_document: default
  html_document: default
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```

```{r library}
library(dplyr)
library(readr)
library(ggplot2)
library(lemur)
library(tidyr)
```

# proximity to services

```{r}
# amenity density
adn <- amenity_density_by_neighbourhood %>% pivot_wider(names_from = amenity_dense, values_from = proportion)
```

```{r}
# core housing needs density
chn <- core_housing_need_by_neighbourhood %>% rename(core_housing_need = prop) %>% select(-prop_group)
```

```{r}
# rental supply
rsn <- neighbourhood_aggregate %>% purrr::transpose() %>% purrr::pluck("rental_supply") %>% 
  bind_rows(.id = "neighbourhood") %>% select(group, neighbourhood, value, prop, market_prop) %>% 
  pivot_wider(names_from = group, values_from = c(value, prop, market_prop))
```

```{r}
# low end of market breakdown
lem <- neighbourhood_aggregate %>% purrr::transpose() %>% purrr::pluck("lem") %>% 
  bind_rows(.id = "neighbourhood") %>% 
  pivot_wider(names_from = Bedrooms, values_from = c(`Deeply Affordable`, `Very Affordable`, `Total`), names_repair = 'minimal')
```

```{r}
# number of buildings
nb <- neighbourhood_aggregate %>% purrr::transpose() %>% purrr::pluck("number_of_buildings") %>% 
  bind_rows(.id = "neighbourhood") %>% 
  pivot_longer(cols = everything()) %>% rename(neighbourhood = name, number_of_buildings = value)
```

```{r}
# total income
ati <- neighbourhood_aggregate %>% purrr::transpose() %>% purrr::pluck("average_total_income") %>% 
  bind_rows(.id = "neighbourhood") %>% 
  pivot_wider(names_from = group, values_from = c(value))
```


```{r}
# unaffordable percent
uh <- neighbourhood_aggregate %>% purrr::transpose() %>% purrr::pluck("unaffordable_housing") %>% 
  bind_rows(.id = "neighbourhood") %>% 
  pivot_longer(cols = everything()) %>% rename(neighbourhood = name, unaffordable_housing = value)
```

```{r}
# average shelter cost
arsc <- neighbourhood_aggregate %>% purrr::transpose() %>% purrr::pluck("average_renter_shelter_cost") %>% 
  bind_rows(.id = "neighbourhood") %>% 
  pivot_longer(cols = everything()) %>% rename(neighbourhood = name, average_renter_shelter_cost = value) 
```

```{r}
# eviction rate
ev <- neighbourhood_aggregate %>% purrr::transpose() %>% purrr::pluck("evictions") %>% 
  bind_rows(.id = "neighbourhood") %>% 
  pivot_longer(cols = everything()) %>% rename(neighbourhood = name, eviction_rate = value)
```


```{r dataset}
proximity_layers <- adn %>% 
  inner_join(arsc, by = 'neighbourhood') %>% 
  inner_join(ati, by = 'neighbourhood') %>% 
  inner_join(lem, by = 'neighbourhood') %>% 
  inner_join(nb, by = 'neighbourhood') %>% 
  inner_join(rsn, by = 'neighbourhood') %>% 
  inner_join(uh, by = 'neighbourhood') %>% 
  inner_join(ev, by = 'neighbourhood') %>% 
  inner_join(chn, by = 'neighbourhood')
```

#lowend similarities

```{r}
proximity_layers %>% filter(neighbourhood == 'West Hill')

```


```{r}
reinf_shap <- proximity_layers %>% 
  select(neighbourhood, Total_Total, eviction_rate, unaffordable_housing, `market_prop_Other Non-Market`, core_housing_need) %>%
  arrange(desc(Total_Total))
```
 
```{r}
plotly::ggplotly(
  ggplot(reinf_shap, aes(core_housing_need, `eviction_rate`, colour = `market_prop_Other Non-Market`)) +
    geom_point(aes(size = Total_Total, text = neighbourhood)) +
    ggrepel::geom_label_repel(data = reinf_shap, aes(label=neighbourhood), size= 2.5) +
    #scale_color_manual(values = c("TRUE" = "#08569a", "FALSE" = "grey")) +
    geom_vline(xintercept = .365) +
    geom_hline(yintercept = .043) +
    #xlim(0, .7) +
    #ylim(0, .7) +
    #geom_abline(a = 1) +
    theme_bw()+
    theme(legend.position = 'None'),
    )
```
 
```{r}
reinf_plot <- reinf_shap %>% mutate(top3 = case_when(neighbourhood == 'Dovercourt-Wallace Emerson-Junction' ~ TRUE,
                          neighbourhood == 'Woburn' ~ TRUE,
                          neighbourhood == 'Weston' ~ TRUE,
                          neighbourhood == 'Thorncliffe Park' ~ TRUE,
                          neighbourhood == 'West Humber-Clairville' ~ TRUE,
                          neighbourhood == 'York University Heights' ~ TRUE,
                          TRUE ~ FALSE))

ggplot(reinf_plot, aes(core_housing_need, `eviction_rate`, colour = `top3`)) +
    geom_point(aes(size = Total_Total, text = neighbourhood)) +
    ggrepel::geom_label_repel(data = reinf_plot %>% filter(top3), aes(label=neighbourhood), size= 2.5) +
    scale_color_manual(values = c("TRUE" = "#08569a", "FALSE" = "grey")) +
    geom_vline(xintercept = .365) +
      geom_text(aes(x=.355, label="City Average", y=0.13), angle=90) +
    geom_hline(yintercept = .043) +
    geom_text(aes(0.075,.043,label = 'City Average', vjust = -1)) +
    theme_bw()+
    theme(legend.position = 'None')
```


#proximity

```{r}
prox_pick <- proximity_layers %>% 
  select(neighbourhood, High, Medium, Low, number_of_buildings, `Total_Total`, `prop_Toronto Community Housing`, eviction_rate) %>% 
  pivot_longer(cols = c(High, Medium, Low))
```

```{r}
graph_prox <- prox_pick %>% filter(Total_Total > 100, number_of_buildings >= 10)


plotly::ggplotly(
  ggplot(graph_prox, aes(value, `Total_Total`, colour = eviction_rate)) +
    geom_point(aes(size = 2, text = neighbourhood)) +
    ggrepel::geom_label_repel(data = graph_prox, aes(label=neighbourhood), size= 2.5) +
    #scale_color_manual(values = c("TRUE" = "#08569a", "FALSE" = "grey")) +
    geom_hline(yintercept = 250) +
    facet_wrap(~name) +
    
    theme_bw()+
    theme(legend.position = 'None')
    )
```





```{r}
triangle <- tibble(polygon_x = c(0,1,.5), polygon_y = c(0,0, sqrt(3)/2))
texts <- tibble(
  x = c(-.025,1.05,.5),
  y = c(0,0,sqrt(3)/2 + .03),
  text = c("Low", "Medium","High"))

woburn <- prox_pick %>% filter(neighbourhood == 'Annex')

pos <-  woburn %>% select("name","value", "neighbourhood", "Total_Total")


positions <- tibble(
  neighbourhood = pos$neighbourhood,
  Total_Total = pos$Total_Total,
  x = as.numeric((1/2) * (((2*pos[which(pos$name == "Medium"),"value"]) + pos[which(pos$name == "High"),"value"])/
                            (pos[which(pos$name == "Low"),"value"] + pos[which(pos$name == "Medium"),"value"]
                             + pos[which(pos$name == "High"),"value"]))),
  y = as.numeric(((sqrt(3)/2) * (pos[which(pos$name == "High"),"value"] / 
                            (pos[which(pos$name == "Low"),"value"] + pos[which(pos$name == "Medium"),"value"]
                             + pos[which(pos$name == "High"),"value"])))))
           
ggplot(positions, aes(x = x, y = y)) +
  geom_point(aes(size = Total_Total/100)) +
  geom_text(label = positions$neighbourhood) +
  geom_text(data = texts, aes(label = text)) +
  geom_polygon(data = triangle,aes(x = polygon_x, y=polygon_y), fill = NA,colour = 'black') +
  xlim(-.1,1.1) +
  ylim(-.1,1.1) +
  theme_void()

```

```{r}
triangle <- tibble(polygon_x = c(0,1,.5), polygon_y = c(0,0, sqrt(3)/2))
texts <- tibble(
  x = c(-.025,1.05,.5),
  y = c(0,0,sqrt(3)/2 + .03),
  text = c("Low", "Medium","High"))

pos <- proximity_layers %>% 
  select(neighbourhood, High, Medium, Low, `Total_Total`, number_of_buildings) #%>% filter(neighbourhood == 'Annex')

ternary <- as_tibble()
for (i in seq(from = 1, to = nrow(pos))){
  positions <- tibble(
    neighbourhood = pos$neighbourhood[i],
    number_of_buildings = pos$number_of_buildings[i],
    Total_Total = pos$Total_Total[i],
    x = as.numeric((1/2) * (((2*pos$Medium[i]) + pos$High[i])/
                              (pos$Low[i] + pos$Medium[i] + pos$High[i]))),
    y = as.numeric(((sqrt(3)/2) * (pos$High[i] / 
                              (pos$Low[i] + pos$Medium[i] + pos$High[i]))))
    )
  for (i in nrow(positions)) {
    ternary <- rbind(ternary, positions)}
}
ternary
```

```{r}
ternary_plot <- ternary %>% filter(Total_Total >= 225)

ggplot(ternary_plot, aes(x = x, y = y)) +
  geom_point(aes(colour = Total_Total)) +
  ggrepel::geom_label_repel(data = ternary_plot, aes(label=neighbourhood), size= 1) +
  #geom_text(label = ternary_plot$neighbourhood, size = 1) +
  geom_text(data = texts, aes(label = text)) +
  geom_polygon(data = triangle,aes(x = polygon_x, y=polygon_y), fill = NA,colour = 'black') +
  xlim(-.1,1.1) +
  ylim(-.1,1.1) +
  theme_void()

```

```{r}
ternary_plot <- pos %>% filter(Total_Total > 250) %>% 
  mutate(top3 = case_when(neighbourhood == 'Dovercourt-Wallace Emerson-Junction' ~ TRUE,
                          neighbourhood == 'Woburn' ~ TRUE,
                          neighbourhood == 'York University Heights' ~ TRUE,
                          neighbourhood == 'Thorncliffe Park' ~ TRUE,
                          neighbourhood == 'West Humber-Clairville' ~ TRUE,
                          neighbourhood == 'Weston' ~ TRUE,
                          TRUE ~ FALSE))



library(ggtern)
ggtern::ggtern(data=ternary_plot,aes(x=Low,y=High, z=Medium)) +
  geom_point(aes(colour = Total_Total), size =2.5) +
  #ggrepel::geom_label_repel(data = ternary_plot, aes(label=neighbourhood), size= 2) +
  geom_text(data = ternary_plot %>% filter(top3)
            , aes(label = paste0(neighbourhood,':',Total_Total)), size = 2, vjust= -3, check_overlap = FALSE,position=position_jitter_tern(y = 0.08)) +
  theme_light() +
  theme_nomask() +
  theme_showarrows() +
  tern_anticlockwise() + 
  theme_nolabels()
```

